import { Metadata } from "next";
import PolicyLayout from "../../components/PolicyLayout";

export const metadata: Metadata = {
  title: "Chatty - Terms & Conditions",
  description: "Terms and conditions for the Chatty app by HeyWrist",
};

export default function ChattyTerms() {
  return (
    <PolicyLayout appName="Chatty" title="Terms & Conditions">
      <p><strong>Effective Date:</strong> April 1, 2026</p>
      <p><strong>Last Updated:</strong> April 1, 2026</p>

      <p>
        These Terms &amp; Conditions (&quot;Terms&quot;) govern your use of the Chatty
        application (&quot;the App&quot;) developed by Hey Wrist (&quot;we,&quot; &quot;us,&quot; or
        &quot;our&quot;). By downloading, installing, or using Chatty, you agree to be
        bound by these Terms.
      </p>

      <h2>1. Description of Service</h2>
      <p>
        Chatty is an AI chatbot application for Apple Watch and iPhone that
        provides conversational AI responses through multiple personas. The App
        is provided for <strong>entertainment and informational purposes
        only</strong>.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least 13 years of age to use the App. By using Chatty,
        you represent that you meet this requirement.
      </p>

      <h2>3. AI-Generated Content Disclaimer</h2>
      <p>
        All responses generated by Chatty are created by on-device AI and
        may contain inaccuracies, errors, or inappropriate content. You
        acknowledge that:
      </p>
      <ul>
        <li>AI responses are <strong>not</strong> a substitute for professional advice of any kind</li>
        <li>You should <strong>not</strong> rely on AI responses for medical, legal, financial, psychological, or other professional guidance</li>
        <li>AI personas are fictional characters and their responses do not represent the views of the developer</li>
        <li>The App does not provide emergency services — if you are in crisis, contact emergency services immediately</li>
        <li>AI responses may occasionally be incorrect, misleading, or nonsensical</li>
      </ul>

      <h2>4. AI Personas</h2>
      <p>
        Chatty includes multiple AI personas with different communication styles.
        These personas are fictional and for entertainment purposes. Any
        resemblance to real persons is coincidental. We do not endorse any
        opinions or advice expressed by AI personas.
      </p>

      <h2>5. In-App Purchases</h2>
      <p>
        Chatty may offer premium features through one-time in-app purchases.
        All purchases are processed by Apple and subject to Apple&apos;s{" "}
        <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" target="_blank" rel="noopener noreferrer">
          Standard EULA
        </a>.
      </p>
      <ul>
        <li>All sales are final. Refunds are handled by Apple.</li>
        <li>Prices may vary by region.</li>
      </ul>

      <h2>6. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the App to generate harmful, illegal, or abusive content</li>
        <li>Rely on AI responses for critical decisions affecting health, safety, or legal matters</li>
        <li>Reverse engineer, decompile, or disassemble the App</li>
        <li>Use the App for any unlawful purpose</li>
        <li>Attempt to extract or replicate the AI models or training data</li>
      </ul>

      <h2>7. Your Content</h2>
      <p>
        Messages you send to AI personas are stored locally on your device. We
        have no access to your conversation content. You are solely responsible
        for the content of your messages.
      </p>

      <h2>8. Intellectual Property</h2>
      <p>
        All content, design, AI models, persona designs, graphics, code, and
        other elements of Chatty are the intellectual property of Hey Wrist.
        You are granted a limited, non-exclusive, non-transferable license for
        personal use.
      </p>

      <h2>9. Disclaimer of Warranties</h2>
      <p>
        The App is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis without
        warranties of any kind. We do not guarantee the accuracy, completeness,
        reliability, or appropriateness of any AI-generated content.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, Hey Wrist shall not be liable
        for any indirect, incidental, special, consequential, or punitive
        damages arising from your use of the App, including:
      </p>
      <ul>
        <li>Decisions made based on AI-generated responses</li>
        <li>Inaccurate, inappropriate, or harmful AI-generated content</li>
        <li>Emotional distress caused by AI interactions</li>
        <li>Loss of conversation data</li>
      </ul>

      <h2>11. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless Hey Wrist from any claims
        arising from your use of the App, your content, or violation of these
        Terms.
      </p>

      <h2>12. Termination</h2>
      <p>
        You may stop using the App at any time by uninstalling it. We reserve
        the right to discontinue or modify the App without prior notice.
      </p>

      <h2>13. Changes to These Terms</h2>
      <p>
        We may modify these Terms at any time. Continued use after changes
        constitutes acceptance.
      </p>

      <h2>14. Governing Law</h2>
      <p>
        These Terms shall be governed by the laws of the jurisdiction in which
        the developer resides.
      </p>

      <h2>15. Contact Us</h2>
      <p>
        <strong>Email:</strong>{" "}
        <a href="mailto:support@heywrist.com">support@heywrist.com</a>
      </p>
      <p><strong>Developer:</strong> Hey Wrist</p>
    </PolicyLayout>
  );
}
