import { Metadata } from "next";
import PolicyLayout from "../../components/PolicyLayout";

export const metadata: Metadata = {
  title: "Sona - Terms & Conditions",
  description: "Terms and conditions for the Sona app by Hey Wrist",
};

export default function SonaTerms() {
  return (
    <PolicyLayout appName="Sona" slug="chatty" title="Terms & Conditions">
      <p><strong>Effective Date:</strong> May 1, 2026</p>
      <p><strong>Last Updated:</strong> May 1, 2026</p>

      <p>
        These Terms &amp; Conditions (&quot;Terms&quot;) govern your use of
        Sona (&quot;the App&quot;), an AI chat companion for Apple Watch and
        iPhone, developed by Hey Wrist (&quot;we,&quot; &quot;us,&quot; or
        &quot;our&quot;). By downloading, installing, or using Sona, you agree
        to be bound by these Terms. If you do not agree, please do not use
        the App.
      </p>

      <h2>1. Description of Service</h2>
      <p>
        Sona provides conversational AI responses through eight personas
        (Sona, Muse, DevBot, FitCoach, ChefAI, Lingua, Tutor, and Calm). AI
        responses are generated by{" "}
        <strong>Microsoft Azure OpenAI Service</strong>, a cloud AI service
        operated by Microsoft Corporation. The App is provided for{" "}
        <strong>entertainment and general informational purposes only</strong>{" "}
        and is <strong>not</strong> a substitute for professional advice of
        any kind.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least 13 years of age to use Sona. The App is rated
        12+ in the App Store. By using Sona, you represent that you meet
        this requirement and that your use complies with the laws of your
        jurisdiction.
      </p>

      <h2>3. AI-Generated Content Disclaimer</h2>
      <p>
        Responses generated by Sona&apos;s AI personas are produced by a
        large language model and may contain inaccuracies, errors,
        omissions, or content that is inappropriate or offensive. You
        acknowledge and agree that:
      </p>
      <ul>
        <li>AI responses are <strong>not</strong> a substitute for professional advice of any kind, including medical, legal, financial, psychological, fitness, nutritional, educational, or therapeutic advice.</li>
        <li>You will <strong>not</strong> rely on AI responses for critical decisions affecting your health, safety, finances, legal rights, or well-being.</li>
        <li>The personas are fictional characters with assigned communication styles. They are <strong>not</strong> licensed professionals and the names &quot;Tutor,&quot; &quot;FitCoach,&quot; &quot;ChefAI,&quot; &quot;Calm,&quot; etc. are illustrative, not credentials.</li>
        <li>Sona is <strong>not</strong> an emergency service. If you are in a medical, mental-health, or safety emergency, contact your local emergency services immediately. If you are in the United States and experiencing thoughts of suicide or self-harm, dial or text 988 (the Suicide &amp; Crisis Lifeline).</li>
        <li>AI responses may occasionally be incorrect, misleading, biased, fabricated, or nonsensical. You are responsible for independently verifying any factual claim before acting on it.</li>
        <li>Image-vision features may misidentify objects, people, or text in your photos.</li>
      </ul>

      <h2>4. AI Personas</h2>
      <p>
        Sona&apos;s personas (Sona, Muse, DevBot, FitCoach, ChefAI, Lingua,
        Tutor, Calm) are fictional characters with assigned conversation
        styles. They are not real people. Any resemblance to real persons,
        living or deceased, is coincidental. Persona responses do{" "}
        <strong>not</strong> represent the views, opinions, or advice of
        Hey Wrist, Microsoft, or any other party.
      </p>

      <h2>5. Sona Pro &mdash; Subscriptions and Lifetime Purchase</h2>
      <p>
        Sona offers an optional <strong>Sona Pro</strong> upgrade that
        unlocks unlimited messages, all eight personas, web grounding,
        image vision, premium themes, and other features described on the
        in-app upgrade screen. Sona Pro is offered in three forms:
      </p>
      <ul>
        <li><strong>Sona Pro Monthly</strong> &mdash; auto-renewing subscription billed monthly. New subscribers receive a 3-day free trial.</li>
        <li><strong>Sona Pro Yearly</strong> &mdash; auto-renewing subscription billed annually. New subscribers receive a 7-day free trial.</li>
        <li><strong>Sona Pro Lifetime</strong> &mdash; one-time non-consumable purchase that grants Sona Pro for the lifetime of the App.</li>
      </ul>
      <p>
        Current pricing in your local currency is displayed on the in-app
        Sona Pro screen and on the App Store product page before purchase.
      </p>

      <h3>5.1 Auto-Renewal Terms (Required Disclosure)</h3>
      <p>
        Subscriptions <strong>automatically renew</strong> at the same
        price and duration as the original term unless cancelled at least{" "}
        <strong>24 hours before the end of the current period</strong>.
        Your Apple ID account will be charged for renewal within 24 hours
        prior to the end of the current period.
      </p>
      <p>
        You can manage your subscription, turn off auto-renewal, or cancel
        at any time:
      </p>
      <ul>
        <li><strong>iPhone:</strong> open iOS Settings &rarr; tap your name at the top &rarr; Subscriptions &rarr; Sona &rarr; Cancel Subscription.</li>
        <li><strong>In-App:</strong> open Sona &rarr; Settings &rarr; Sona Pro &rarr; Manage Subscription. This deep-links to the same iOS subscriptions screen.</li>
      </ul>
      <p>
        Cancelling stops auto-renewal but does not refund the current
        period. You retain Pro features until the end of the current
        billing period.
      </p>

      <h3>5.2 Free Trials</h3>
      <p>
        Free trials are available only to first-time Sona Pro
        subscribers, one trial per Apple ID across the Sona Pro
        subscription group. If you cancel before the trial ends, you will
        not be charged. If you do not cancel, the subscription
        automatically converts to a paid subscription at the end of the
        trial.
      </p>

      <h3>5.3 Refunds</h3>
      <p>
        All payments are processed by Apple. Refunds are handled solely by
        Apple under{" "}
        <a href="https://support.apple.com/en-us/HT204084" target="_blank" rel="noopener noreferrer">
          Apple&apos;s refund policy
        </a>
        . To request a refund, visit{" "}
        <a href="https://reportaproblem.apple.com" target="_blank" rel="noopener noreferrer">
          reportaproblem.apple.com
        </a>
        . Hey Wrist cannot issue refunds directly. Statutory refund rights
        under your local consumer-protection laws (for example the EU
        14-day cooling-off period for digital subscriptions) are
        unaffected by this clause.
      </p>

      <h3>5.4 Price Changes</h3>
      <p>
        We may change the price of subscriptions in accordance with App
        Store rules. Apple will notify you of material price increases and
        require your explicit consent before charging the new price.
      </p>

      <h3>5.5 Family Sharing</h3>
      <p>
        Sona Pro Lifetime is enabled for Family Sharing. Auto-renewing
        subscriptions (Monthly and Yearly) are <strong>not</strong>{" "}
        Family-Shared and grant access only to the purchasing Apple ID.
      </p>

      <h3>5.6 Standard EULA</h3>
      <p>
        Use of the App is subject to Apple&apos;s{" "}
        <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" target="_blank" rel="noopener noreferrer">
          Standard EULA
        </a>
        , which applies to all licensed App Store applications. In the
        event of a conflict between these Terms and the Standard EULA,
        these Terms control with respect to subjects on which they
        explicitly differ; the Standard EULA controls for all other
        subjects.
      </p>

      <h2>6. Free Tier and Usage Limits</h2>
      <p>
        Sona offers a free tier with the following limits:
      </p>
      <ul>
        <li>10 AI messages per 24-hour rolling period.</li>
        <li>Access to the default Sona persona only.</li>
        <li>No image-vision input.</li>
      </ul>
      <p>
        Limits reset every 24 hours. Limits may be adjusted in future
        versions of the App; we will not retroactively reduce features
        already paid for.
      </p>

      <h2>7. Acceptable Use</h2>
      <p>You agree not to use the App to:</p>
      <ul>
        <li>Generate or solicit content that is illegal, defamatory, harassing, hateful, sexually explicit involving minors, or that incites violence.</li>
        <li>Generate content intended to deceive others (such as impersonation, phishing, or fraud).</li>
        <li>Make critical decisions affecting health, safety, finances, or legal rights based solely on AI output.</li>
        <li>Submit content protected by attorney-client privilege, doctor-patient privilege, or any non-disclosure obligation that would be breached by transmission to a third-party AI service.</li>
        <li>Submit content of third parties without their consent where required by law.</li>
        <li>Attempt to extract, replicate, or reverse-engineer the underlying AI models, system prompts, or training data.</li>
        <li>Reverse-engineer, decompile, disassemble, or otherwise attempt to derive the source code of the App.</li>
        <li>Use the App to violate Microsoft&apos;s{" "}
          <a href="https://www.microsoft.com/en-us/legal/terms-of-use" target="_blank" rel="noopener noreferrer">
            terms of service
          </a>{" "}or the{" "}
          <a href="https://learn.microsoft.com/en-us/legal/cognitive-services/openai/code-of-conduct" target="_blank" rel="noopener noreferrer">
            Azure OpenAI Code of Conduct
          </a>
          .
        </li>
        <li>Attempt to circumvent the free-tier limit, the Pro entitlement gate, or any other technical restriction.</li>
      </ul>
      <p>
        Misuse of the App may result in termination of your access and, in
        the case of Microsoft Azure OpenAI&apos;s abuse-monitoring
        process, may be reported to Microsoft.
      </p>

      <h2>8. Your Content</h2>
      <p>
        You retain ownership of the messages, images, and prompts you
        submit to Sona (&quot;Your Content&quot;). By submitting Your
        Content you grant Hey Wrist a limited, non-exclusive,
        royalty-free, worldwide license to transmit Your Content to
        Microsoft Azure OpenAI for the sole purpose of generating an AI
        response and returning it to you.
      </p>
      <p>
        We do not use Your Content to train AI models. Microsoft does not
        use Your Content to train OpenAI&apos;s or Microsoft&apos;s
        foundation models (see Section 2 of our{" "}
        <a href="/chatty/privacy">Privacy Policy</a>
        ).
      </p>
      <p>
        You are solely responsible for the legality of Your Content and
        for any consequences of submitting it. You represent that you
        have all necessary rights to submit Your Content.
      </p>

      <h2>9. Intellectual Property</h2>
      <p>
        All trademarks, branding, design, persona names and personalities,
        artwork, copy, source code, and other elements of Sona are the
        intellectual property of Hey Wrist or its licensors. Subject to
        these Terms, we grant you a limited, non-exclusive,
        non-transferable, revocable license to use Sona for personal,
        non-commercial purposes on iOS and watchOS devices you own or
        control.
      </p>
      <p>
        Apple, Apple Watch, iPhone, App Store, watchOS, and iOS are
        trademarks of Apple Inc.
      </p>

      <h2>10. Third-Party Services</h2>
      <p>
        Sona transmits content to Microsoft Azure OpenAI Service, sends
        anonymous usage analytics to Mixpanel (opt-out available in
        Settings), sends crash diagnostics to our internal bug-reporting
        service, and uses Apple StoreKit for in-app purchases. Each of
        these services is governed by its own terms; see our{" "}
        <a href="/chatty/privacy">Privacy Policy</a> for the full
        breakdown. Your use of Sona constitutes acceptance of those terms
        as they apply to data we transmit to those services on your
        behalf.
      </p>

      <h2>11. Disclaimer of Warranties</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE APP IS
        PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot;
        BASIS WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
        INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
        PURPOSE, NON-INFRINGEMENT, ACCURACY, OR THAT THE APP WILL BE
        UNINTERRUPTED OR ERROR-FREE. WE DO NOT WARRANT THE ACCURACY,
        COMPLETENESS, RELIABILITY, OR APPROPRIATENESS OF ANY AI-GENERATED
        CONTENT. THIS DISCLAIMER DOES NOT EXCLUDE OR LIMIT WARRANTIES
        THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.
      </p>

      <h2>12. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, HEY WRIST,
        ITS OFFICERS, EMPLOYEES, AND AFFILIATES SHALL NOT BE LIABLE FOR
        ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
        DAMAGES, OR FOR ANY LOSS OF PROFITS, REVENUE, DATA, GOODWILL, OR
        OTHER INTANGIBLE LOSSES ARISING FROM OR RELATED TO YOUR USE OF
        THE APP, INCLUDING:
      </p>
      <ul>
        <li>Decisions made based on AI-generated responses.</li>
        <li>Inaccurate, inappropriate, or harmful AI-generated content.</li>
        <li>Emotional distress caused by AI interactions.</li>
        <li>Loss of locally stored conversation data, persona memories, streaks, or starred messages.</li>
        <li>Service interruptions, including outages of Microsoft Azure OpenAI.</li>
      </ul>
      <p>
        Hey Wrist&apos;s aggregate liability for any claim arising from
        these Terms or your use of the App shall not exceed the greater
        of (a) the amount you paid Hey Wrist (via Apple) for Sona Pro in
        the twelve months preceding the claim, or (b) USD $50. This
        limitation does not apply to liability that cannot be excluded
        under applicable law (such as gross negligence, wilful
        misconduct, or statutory consumer rights).
      </p>

      <h2>13. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless Hey Wrist from any
        claims, losses, liabilities, damages, costs, and expenses
        (including reasonable attorneys&apos; fees) arising from (a) Your
        Content, (b) your violation of these Terms, (c) your violation of
        any law or third-party right, or (d) your misuse of the App
        including circumvention of usage limits or abuse of the AI
        service.
      </p>

      <h2>14. Termination</h2>
      <p>
        You may stop using the App at any time by uninstalling it. We
        reserve the right to suspend or terminate your access to the App
        at any time, with or without notice, if you violate these Terms,
        if Microsoft suspends our access to Azure OpenAI for content you
        submitted, or if continued operation becomes commercially or
        technically impractical. Termination does not entitle you to a
        refund of subscription fees beyond what Apple grants under its
        refund policy.
      </p>

      <h2>15. Changes to These Terms</h2>
      <p>
        We may modify these Terms from time to time. Material changes
        will be reflected in the &quot;Last Updated&quot; date at the
        top, and where the change materially affects your rights we will
        surface a notice in the App the next time you open it. Continued
        use of Sona after changes take effect constitutes acceptance.
      </p>

      <h2>16. Governing Law and Disputes</h2>
      <p>
        These Terms are governed by the laws of <strong>India</strong>
        , without regard to conflict-of-laws principles. Any dispute
        arising from these Terms or your use of the App shall be subject
        to the exclusive jurisdiction of the courts of{" "}
        <strong>Bengaluru, Karnataka, India</strong>, except where
        applicable consumer-protection law gives you the right to bring
        proceedings in your country of residence.
      </p>
      <p>
        If any provision of these Terms is held unenforceable, the
        remaining provisions remain in full force and effect.
      </p>

      <h2>17. Contact Us</h2>
      <p>
        <strong>Email:</strong>{" "}
        <a href="mailto:founder@heywrist.com">founder@heywrist.com</a>
      </p>
      <p><strong>Developer:</strong> Hey Wrist</p>
    </PolicyLayout>
  );
}
